# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paft.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 476)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.respostas = QtWidgets.QLineEdit(self.centralwidget)
        self.respostas.setGeometry(QtCore.QRect(10, 70, 261, 51))
        self.respostas.setObjectName("respostas")
        self.btnA = QtWidgets.QPushButton(self.centralwidget)
        self.btnA.setGeometry(QtCore.QRect(10, 190, 121, 51))
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(150, 190, 121, 51))
        self.btnB.setObjectName("btnB")
        self.Enviar = QtWidgets.QPushButton(self.centralwidget)
        self.Enviar.setGeometry(QtCore.QRect(10, 130, 261, 51))
        self.Enviar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Enviar.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Enviar.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("audio-volume-low")
        self.Enviar.setIcon(icon)
        self.Enviar.setAutoExclusive(False)
        self.Enviar.setAutoRepeatDelay(300)
        self.Enviar.setAutoDefault(False)
        self.Enviar.setDefault(False)
        self.Enviar.setFlat(False)
        self.Enviar.setObjectName("Enviar")
        self.caixinha = QtWidgets.QTextBrowser(self.centralwidget)
        self.caixinha.setGeometry(QtCore.QRect(300, 70, 256, 341))
        self.caixinha.setObjectName("caixinha")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 631, 521))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(213, 193, 255);\n"
"background-color: rgb(51, 61, 117);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(150, 260, 121, 71))
        self.pushButton.setStyleSheet("background-color: rgb(183, 214, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 571, 61))
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);\n"
"font: 28pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 111, 19))
        self.label_3.setStyleSheet("font: 700 12pt \"Century Schoolbook\";\n"
"color: rgb(128, 255, 164);\n"
"color: rgb(184, 184, 184);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-20, 440, 691, 221))
        self.label.setStyleSheet("font: 700 28pt \"Yu Gothic\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(206, 195, 116);")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 260, 121, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(183, 214, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 340, 261, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(183, 214, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(300, 70, 301, 341))
        self.textEdit.setObjectName("textEdit")
        self.frame.raise_()
        self.respostas.raise_()
        self.btnA.raise_()
        self.btnB.raise_()
        self.Enviar.raise_()
        self.caixinha.raise_()
        self.textEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnA.setText(_translate("MainWindow", "Opção A"))
        self.btnB.setText(_translate("MainWindow", "Opção B"))
        self.Enviar.setText(_translate("MainWindow", "Enviar"))
        self.pushButton.setText(_translate("MainWindow", "Seguir -->"))
        self.label_2.setText(_translate("MainWindow", "Aventura do cara peladão"))
        self.label_3.setText(_translate("MainWindow", "Escreva aqui"))
        self.label.setText(_translate("MainWindow", "           Aperte \"seguir\" para jogar"))
        self.pushButton_3.setText(_translate("MainWindow", "<-- Voltar"))
        self.pushButton_2.setText(_translate("MainWindow", "Resetar"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI\'; font-size:10.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt;\">Olá jogador! </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt;\">Seja bem-vindo a aventura.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Você deve apertar  o botão seguir para dar continuidade a história.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Quando for pedido para que você faça uma escolha aperte um dos botões (A ou B) e depois clique em seguir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Para escrever na caixa de texto clique na caixa, escreva, clique em enviar e depois em seguir!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Você pode clicar em voltar para voltar a um momento anterior da historia.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
